Import libraries

In [147]:
import pandas as pd
import numpy as np

Import dataset

In [148]:
df = pd.read_csv("/content/Data set for DADS June.csv")

In [149]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [150]:
df.shape

(1328, 8)

In [151]:
df.columns

Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [153]:
df.describe(include="all")

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
count,1328,1328,1328,1328,1328,1328.000000,1328,1328
unique,617,832,283,3,1141,NaN,4,1307
top,2024-02-07,16:19,POS SWIGGY BANGALORE,DR,"Rs. 15,000",NaN,UPI,TXN427270
freq,6,6,30,670,5,NaN,1299,2
mean,NaN,NaN,NaN,NaN,NaN,147805.330572,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,341059.809969,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-769127.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,-104585.750000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,151650.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,448324.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,720079.000000,NaN,NaN

In [154]:
df.isnull().sum()

Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [155]:
df.duplicated().sum()

np.int64(18)

In [156]:
print(df["Type"].unique())
print(df["Mode"].unique())

['Debit' 'DR' 'CR']
['UPI' 'NEFT' 'IMPS' 'ATM']

Data Cleaning

In [157]:
df["Date"].head(20)

0      2024-01-01
1       01-Jan-24
2       01-Jan-24
3      2024-01-01
4     01 Jan 2024
5      2024-01-01
6      2024-01-01
7       01-Jan-24
8      2024-01-02
9        02/01/24
10       02/01/24
11      02-Jan-24
12       02/01/24
13    02 Jan 2024
14      02-Jan-24
15       02/01/24
16     2024-01-02
17       02/01/24
18      03-Jan-24
19       03/01/24
Name: Date, dtype: object

In [158]:
df["Date"].unique()[:20]

array(['2024-01-01', '01-Jan-24', '01 Jan 2024', '2024-01-02', '02/01/24',
       '02-Jan-24', '02 Jan 2024', '03-Jan-24', '03/01/24', '2024-01-03',
       '04-Jan-24', '2024-01-04', '04 Jan 2024', '04/01/24', '05-Jan-24',
       '05/01/24', '2024-01-05', '06 Jan 2024', '06/01/24', '06-Jan-24'],
      dtype=object)

In [159]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed", dayfirst=True)

In [160]:
df["Date"].dtype

dtype('<M8[ns]')

In [161]:
df["Date"].head()

0   2024-01-01
1   2024-01-01
2   2024-01-01
3   2024-01-01
4   2024-01-01
Name: Date, dtype: datetime64[ns]

In [162]:
df["Amount"].head(10)

0      ₹2462
1      50.00
2     ₹84728
3      ₹1828
4     270.00
5    Rs. 625
6    Rs. 148
7       ₹482
8    Rs. 537
9       3956
Name: Amount, dtype: object

Clean the Amount column

In [163]:
df["Amount"] = (
    df["Amount"]
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

In [164]:
df["Amount"] = pd.to_numeric(df["Amount"])

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   datetime64[ns]
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   float64
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 83.1+ KB

Verify the data coloumn

In [166]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed", dayfirst=True)

In [167]:
df["Date"].dtype

dtype('<M8[ns]')

duplicate rows

In [168]:
duplicates = df[df.duplicated()]
duplicates

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
92,2024-01-13,19:40,BHIM-BLINKIT,DR,306.0,608435.0,UPI,TXN829168
122,2024-01-18,10:22,TUMMOC-BMTC,Debit,45.0,586624.0,UPI,TXN943700
149,2024-01-22,19:12,UPI-IOC9075@HDFCBANK,Debit,7264.0,-378160.0,UPI,TXN734252
282,2024-02-09,16:13,POS ZEPTO BANGALORE,Debit,617.0,465428.0,UPI,TXN574514
372,2024-02-21,12:28,TUMMOC-BMTC,DR,25.0,401150.0,UPI,TXN427270
476,2024-03-05,21:33,UPI-AMAZONPAY@HDFCBANK,Debit,19917.0,-465439.0,UPI,TXN674071
568,2024-03-18,13:44,Swiggy*Order,DR,383.0,247011.0,UPI,TXN346249
806,2024-04-20,23:03,Swiggy*Order,Debit,559.0,46778.0,UPI,TXN176523
816,2024-04-21,20:28,ZOMATO BENGALURU,DR,682.0,43697.0,UPI,TXN274169
965,2024-05-12,20:55,POS SWIGGY BANGALORE,DR,615.0,-45370.0,UPI,TXN390956
983,2024-05-15,13:52,UPI-ZEPTO-2913@HDFCBANK,DR,642.0,-63547.0,UPI,TXN819391
985,2024-05-15,14:13,UPI-FLIPKART@HDFCBANK,Debit,14416.0,-495231.0,UPI,TXN508819
1062,2024-05-25,17:26,POS SWIGGY-RESTAURANT,Debit,618.0,-130536.0,UPI,TXN438560
1067,2024-05-25,21:36,ZOMATO-DINING,Debit,407.0,-132435.0,UPI,TXN453737
1146,2024-06-06,11:09,UPI-ZOMATO5117@OKICICI,DR,649.0,-196117.0,UPI,TXN338777
1170,2024-06-09,07:09,POS SWIGGY BANGALORE,Debit,232.0,-220615.0,UPI,TXN172956
1175,2024-06-09,18:38,BANGALORE ELEC SUPPLY,DR,2331.0,681057.0,UPI,TXN493537
1241,2024-06-18,17:58,UPI-VIKAS-1878@OKAXIS,Debit,1099.0,-719544.0,UPI,TXN527265

In [169]:
before = len(df)

df = df.drop_duplicates()

after = len(df)

print(f"Rows before : {before}")
print(f"Rows after  : {after}")
print(f"Duplicates removed : {before-after}")

Rows before : 1328
Rows after  : 1310
Duplicates removed : 18

In [170]:
df[df.duplicated(keep=False)].sort_values(
    by=["Date", "Time", "Amount"]
)

Empty DataFrame
Columns: [Date, Time, Description, Type, Amount, Balance, Mode, Ref]
Index: []

Standardize the Type column

In [171]:
df["Type"].value_counts()

Type
DR       662
Debit    642
CR         6
Name: count, dtype: int64

In [172]:
df["Type"] = df["Type"].replace({
    "DR": "Debit",
    "CR": "Credit"
})

In [173]:
df["Type"].value_counts()

Type
Debit     1304
Credit       6
Name: count, dtype: int64

Create new date features

In [174]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day
df["Day_Name"] = df["Date"].dt.day_name()

Hour coloumn

In [175]:
df["Hour"] = pd.to_datetime(df["Time"], format="%H:%M").dt.hour

In [176]:
df[["Time", "Hour"]].head()

    Time  Hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14

Vendor Extraction

In [177]:
df["Description"].sample(50, random_state=42)

708           POS ZEPTO BANGALORE
1006            ZEPTO MARKETPLACE
354        UPI-UBER-1232@HDFCBANK
998            UBER SYSTEMS INDIA
414      POS BANGALORE RESTAURANT
926         UPI-SWIGGY8720@OKAXIS
914            UPI-STARBUCKS@AXIS
1131             SWIGGY-INSTAMART
1185      UPI-ZEPTO-5207@HDFCBANK
348                    BHIM ZEPTO
1233           UPI-STARBUCKS@AXIS
1058         POS SWIGGY BANGALORE
234        UPI-BLINKIT-3798@PAYTM
959              BESCOM ELEC BILL
195                    POS MYNTRA
746        UPI-BIGBASKET@HDFCBANK
356           POS CAFE COFFEE DAY
1076         BUNDL TECH-INSTAMART
560                 BMTC BUS PASS
367             INNOVATIVE RETAIL
65                 TATA STARBUCKS
102      POS INDIAN OIL BANGALORE
1133                 AMZN-INTPYMT
1063        POS SWIGGY-RESTAURANT
1132        UPI-SWIGGY8392@OKAXIS
1039                   POS ZOMATO
1323             SWIGGY-INSTAMART
627     UPI-RESTAURANT-0753@PAYTM
728       UPI-BOOKMYSHOW@HDFCBANK
199              ZOMATO MEDIA P L
689         POS THIRD WAVE COFFEE
984         UPI-FLIPKART@HDFCBANK
51                    BHIM SWIGGY
820                   POS BLINKIT
116                UPI-NYKAA@AXIS
876          UPI-THIRDWAVE@OKAXIS
1286              AIRTEL POSTPAID
751              RAPIDO BIKE TAXI
990           INSTAMART BANGALORE
1246     POS BANGALORE RESTAURANT
882       POS STARBUCKS BANGALORE
313              Amazon Pay India
432         POS THIRD WAVE COFFEE
771               KIRANAKART TECH
1219                 Swiggy*Order
538             ZEPTO MARKETPLACE
63          POS SWIGGY-RESTAURANT
555                BUNDL Tech P L
1304          POS ZEPTO BANGALORE
702        UPI-ZOMATO9481@OKICICI
Name: Description, dtype: object

In [178]:
df["Description"].value_counts().head(100)

Description
SWIGGY-INSTAMART                    29
POS SWIGGY BANGALORE                28
ZOMATO MEDIA P L                    26
Swiggy*Order                        26
UPI-RAPIDO@OKAXIS                   24
POS SWIGGY-RESTAURANT               24
POS ZOMATO                          23
BHIM SWIGGY                         23
ZOMATO BENGALURU                    22
OLA CABS                            21
UBER INDIA                          20
ZOMATO-DINING                       20
OLA ELECTRIC                        20
POS ZEPTO BANGALORE                 19
Amazon Pay India                    19
ANI Technologies                    18
UBER SYSTEMS INDIA                  18
BUNDL Tech P L                      18
POS OLA-PRIME                       18
RAPIDO BIKE TAXI                    17
UPI-STARBUCKS@AXIS                  17
INSTAMART BANGALORE                 16
BHIM ZEPTO                          16
UPI-ZOMATO-LIMITED@PAYTM            16
GROFERS INDIA P L                   15
POS UBER BANGALORE                  15
AMAZONIN MARKETPLACE                15
ROPPEN TRANSPORTATION               14
TUMMOC-BMTC                         14
ZEPTO MARKETPLACE                   13
KIRANAKART TECH                     13
POS EMPIRE RESTAURANT               13
UPI-FLIPKART@HDFCBANK               13
FLIPKART INDIA                      13
POS STARBUCKS BANGALORE             13
BHIM-BLINKIT                        13
POS FLIPKART BANGALORE              13
UPI-AMAZONPAY@HDFCBANK              12
BMTC BUS PASS                       12
POS BANGALORE RESTAURANT            12
POS MEGHANA FOODS                   12
TATA STARBUCKS                      12
AMZN-INTPYMT                        11
POS THIRD WAVE COFFEE               11
POS NYKAA BANGALORE                 11
BHIM-BMTC                           11
COFFEE DAY GLOBAL                   11
POS INDIAN OIL BANGALORE            11
UPI-THIRDWAVE@OKAXIS                11
POS DINEOUT                         10
AMAZON IN                           10
AVENUE SUPERMARTS                   10
UPI-OLACABS@HDFCBANK                10
UPI-MYNTRA@HDFCBANK                 10
POS HP PETROL STATION                9
AMAZON SELLER SVCS                   9
TWC INDIA                            9
POS TRUFFLES                         9
UPI-SWIGGY-INSTAMART@OKAXIS          9
UPI-CCD@HDFCBANK                     9
UPI-DMART@OKAXIS                     9
BUNDL TECH-INSTAMART                 9
INNOVATIVE RETAIL                    8
POS BLINKIT                          8
BLINKIT BANGALORE                    8
Uber*Trip                            7
BMS MOVIE TICKETS                    7
BANGALORE ELEC SUPPLY                6
POS CAFE COFFEE DAY                  6
IMPS ZERODHA-COIN                    6
DISNEY HOTSTAR                       6
UPI-BIGBASKET@HDFCBANK               6
UPI-GROWWPAY@HDFCBANK                6
NEFT-TECHCRUSH LABS-SALARY MAY24     6
MYNTRA DESIGNS                       5
BESCOM ELEC BILL                     5
AMZN PRIME                           5
BIGBASKET BANGALORE                  5
BWSSB WATER BILL                     5
FKART INTRNET                        4
UPI-ZERODHA-COIN@AXIS                4
UPI-NETFLIX-MEMB@HDFCBANK            4
AIRTEL POSTPAID                      4
UPI-BOOKMYSHOW@HDFCBANK              4
POS INSTAMART                        4
UPI-BESCOM-BILL@HDFCBANK             4
UPI-HOTSTAR@AXIS                     4
AMAZON PRIME VIDEO                   4
Flipkart Internet                    4
RELIANCE JIO                         4
UPI-SPOTIFY-IN@AXIS                  3
NETFLIX ENTERTAINMENT                3
FSN E-COMMERCE                       3
POS MYNTRA                           3
POS DMART BANGALORE                  3
UPI-NYKAA@AXIS                       3
VI POSTPAID                          3
UPI-BWSSB@AXIS                       3
STAR INDIA PVT LTD                   3
UPI-VI-RECHARGE@HDFCBANK             3
Name: count, dtype: int64

Vendor dictionary

In [179]:
vendor_dict = {
    "Swiggy": ["SWIGGY"],
    "Zomato": ["ZOMATO"],
    "Blinkit": ["BLINKIT"],
    "Zepto": ["ZEPTO"],
    "Amazon": ["AMAZON"],
    "Flipkart": ["FLIPKART"],
    "Uber": ["UBER"],
    "Ola": ["OLA"],
    "Netflix": ["NETFLIX"],
    "Spotify": ["SPOTIFY"],
    "BookMyShow": ["BOOKMYSHOW"],
    "Airtel": ["AIRTEL"],
    "Jio": ["JIO"],
    "Electricity": ["ELECTRIC"],
    "ATM": ["ATM"],
    "Salary": ["SALARY"],
}

vendor_dict.update({
    "BMTC": ["BMTC"],
    "Groww": ["GROWW"],
    "BookMyShow": ["BMS", "BOOKMYSHOW"],
    "Starbucks": ["STARBUCKS"],
    "Third Wave Coffee": ["THIRDWAVE", "TWC INDIA"],
    "Truffles": ["TRUFFLES"],
    "Instamart": ["INSTAMART"],
    "Grofers": ["GROFERS"],
    "BESCOM": ["BESCOM", "BANGALORE ELEC"],
    "Rapido": ["ROPPEN"],
    "ANI Technologies": ["ANI TECHNOLOGIES"],
    "BMTC": ["BMTC"],
    "Groww": ["GROWW"],
    "BookMyShow": ["BMS", "BOOKMYSHOW"],
    "Starbucks": ["STARBUCKS"],
    "Third Wave Coffee": ["THIRDWAVE", "TWC INDIA"],
    "Truffles": ["TRUFFLES"],
    "Instamart": ["INSTAMART"],
    "Grofers": ["GROFERS"],
    "BESCOM": ["BESCOM", "BANGALORE ELEC"],
    "Rapido": ["ROPPEN"],
    "ANI Technologies": ["ANI TECHNOLOGIES"],
    # Transport
    "Rapido": ["RAPIDO"],

    # Food Delivery
    "Swiggy": ["BUNDL"],

    # Grocery
    "BigBasket": ["BIGBASKET", "KIRANAKART"],
    "DMart": ["DMART", "AVENUE SUPERMARTS"],
    "Reliance Fresh": ["INNOVATIVE RETAIL"],

    # Restaurants
    "Empire Restaurant": ["EMPIRE"],
    "Meghana Foods": ["MEGHANA"],
    "Restaurant": ["RESTAURANT"],
    "Dineout": ["DINEOUT"],

    # Coffee
    "Cafe Coffee Day": ["CCD", "COFFEE DAY"],
    "Third Wave Coffee": ["THIRD WAVE"],

    # Shopping
    "Nykaa": ["NYKAA", "FSN E-COMMERCE"],
    "Myntra": ["MYNTRA"],
    "Amazon Prime": ["AMZN PRIME"],
    "Amazon": ["AMZN"],

    # Fuel
    "Indian Oil": ["INDIAN OIL", "IOC"],
    "HP Petrol": ["HP PETROL"],
    "BPCL": ["BPCL"],

    # Entertainment
    "Disney Hotstar": ["HOTSTAR", "STAR INDIA"],
    "BookMyShow": ["BIGTREE"],

    # Utilities
    "BWSSB": ["BWSSB"],
    "Vodafone Idea": ["VODAFONE", "VI POSTPAID", "VI-RECHARGE"],

    # Investment
    "Zerodha": ["ZERODHA"],

    # Rent
    "Rent": ["RENT-LANDLORD"]
})

vendor_dict.update({

    # Personal Transfers
    "P2P Transfer": [
        "AMAN",
        "ANKIT",
        "PRIYA",
        "SNEHA",
        "NEHA",
        "VIKAS",
        "KARAN"
    ],

    # Cash Withdrawal
    "Cash Withdrawal": [
        "ATM"
    ]
})

In [180]:
def extract_vendor(desc):
    desc = str(desc).upper()

    for vendor, keywords in vendor_dict.items():
        for keyword in keywords:
            if keyword in desc:
                return vendor

    return "Others"

In [181]:
df["Vendor"] = df["Description"].apply(extract_vendor)

In [182]:
df["Vendor"].value_counts()

Vendor
Others               253
Zomato               121
Uber                  71
Ola                   69
Instamart             58
Zepto                 58
Restaurant            53
Flipkart              43
Starbucks             42
Rapido                41
Blinkit               40
BMTC                  37
Swiggy                27
Cafe Coffee Day       26
BigBasket             24
DMart                 22
Myntra                20
Nykaa                 19
P2P Transfer          18
ANI Technologies      18
Indian Oil            17
ATM                   17
Amazon                16
BESCOM                15
Grofers               15
Zerodha               14
Disney Hotstar        13
Empire Restaurant     13
Meghana Foods         12
Third Wave Coffee     11
Netflix               10
Dineout               10
Groww                  9
HP Petrol              9
Truffles               9
Reliance Fresh         8
BWSSB                  8
Spotify                8
Vodafone Idea          8
Salary                 6
Jio                    6
Rent                   6
Airtel                 6
BPCL                   2
BookMyShow             2
Name: count, dtype: int64

In [183]:
df[["Description", "Vendor"]].head(30)

                         Description            Vendor
0                 AMAZON SELLER SVCS            Others
1                          BHIM-BMTC              BMTC
2   NEFT-TECHCRUSH LABS-SALARY MAY24            Salary
3               UPI-AMAN-8934@OKAXIS      P2P Transfer
4                       BHIM-BLINKIT           Blinkit
5                         BHIM ZEPTO             Zepto
6             UPI-UBER-2426@HDFCBANK              Uber
7                       BHIM-BLINKIT           Blinkit
8               POS SWIGGY BANGALORE            Others
9              UPI-GROWWPAY@HDFCBANK             Groww
10                      OLA ELECTRIC               Ola
11                 BMS MOVIE TICKETS            Others
12                     POS OLA-PRIME               Ola
13                  SWIGGY-INSTAMART         Instamart
14                UPI-STARBUCKS@AXIS         Starbucks
15              UPI-THIRDWAVE@OKAXIS            Others
16                  ANI Technologies  ANI Technologies
17                     BMTC BUS PASS              BMTC
18                      POS TRUFFLES          Truffles
19                    FLIPKART INDIA          Flipkart
20             POS SWIGGY-RESTAURANT        Restaurant
21                 GROFERS INDIA P L           Grofers
22                POS UBER BANGALORE              Uber
23             POS SWIGGY-RESTAURANT        Restaurant
24             BANGALORE ELEC SUPPLY            BESCOM
25                         TWC INDIA            Others
26          UPI-BESCOM-BILL@HDFCBANK            BESCOM
27              UPI-AMAN-0816@OKAXIS      P2P Transfer
28             ROPPEN TRANSPORTATION            Others
29                UPI-STARBUCKS@AXIS         Starbucks

In [184]:
others = df[df["Vendor"] == "Others"]
others["Description"].value_counts().head(100)

Description
POS SWIGGY BANGALORE         28
Swiggy*Order                 26
BHIM SWIGGY                  23
Amazon Pay India             19
AMAZONIN MARKETPLACE         15
ROPPEN TRANSPORTATION        14
UPI-AMAZONPAY@HDFCBANK       12
UPI-THIRDWAVE@OKAXIS         11
AMAZON IN                    10
AMAZON SELLER SVCS            9
TWC INDIA                     9
BMS MOVIE TICKETS             7
UPI-BOOKMYSHOW@HDFCBANK       4
FKART INTRNET                 4
AMAZON PRIME VIDEO            4
UPI-SWIGGY0226@OKAXIS         2
UPI-SWIGGY-6560@HDFCBANK      1
UPI-SWIGGY-9474@HDFCBANK      1
UPI-SWIGGY-2954@HDFCBANK      1
UPI-SWIGGY-5808@HDFCBANK      1
UPI-SWIGGY-5551@HDFCBANK      1
UPI-SWIGGY-7959@HDFCBANK      1
UPI-SWIGGY2461@OKAXIS         1
UPI-SWIGGY9672@OKAXIS         1
UPI-SWIGGY4619@OKAXIS         1
UPI-SWIGGY3675@OKAXIS         1
UPI-SWIGGY1616@OKAXIS         1
UPI-SWIGGY-1309@HDFCBANK      1
UPI-SWIGGY-5933@HDFCBANK      1
UPI-SWIGGY8086@OKAXIS         1
UPI-SWIGGY-6605@HDFCBANK      1
UPI-SWIGGY-7844@HDFCBANK      1
UPI-SWIGGY-1487@HDFCBANK      1
UPI-SWIGGY-7642@HDFCBANK      1
UPI-SWIGGY-8169@HDFCBANK      1
UPI-SWIGGY1600@OKAXIS         1
UPI-SWIGGY8576@OKAXIS         1
UPI-SWIGGY5466@OKAXIS         1
UPI-SWIGGY-2664@HDFCBANK      1
UPI-SWIGGY5057@OKAXIS         1
UPI-SWIGGY4144@OKAXIS         1
UPI-SWIGGY-9575@HDFCBANK      1
UPI-SWIGGY9328@OKAXIS         1
UPI-SWIGGY9600@OKAXIS         1
UPI-SWIGGY-3513@HDFCBANK      1
UPI-SWIGGY1998@OKAXIS         1
UPI-SWIGGY0250@OKAXIS         1
UPI-SWIGGY0894@OKAXIS         1
UPI-SWIGGY6412@OKAXIS         1
UPI-SWIGGY-1791@HDFCBANK      1
UPI-SWIGGY5867@OKAXIS         1
UPI-SWIGGY-4758@HDFCBANK      1
UPI-SWIGGY4389@OKAXIS         1
UPI-SWIGGY8720@OKAXIS         1
UPI-SWIGGY9756@OKAXIS         1
UPI-SWIGGY-1714@HDFCBANK      1
UPI-SWIGGY-6024@HDFCBANK      1
UPI-SWIGGY5737@OKAXIS         1
UPI-AMAZON-PRIME@HDFCBANK     1
UPI-SWIGGY2847@OKAXIS         1
UPI-SWIGGY9088@OKAXIS         1
UPI-SWIGGY9983@OKAXIS         1
UPI-SWIGGY8392@OKAXIS         1
UPI-SWIGGY1418@OKAXIS         1
UPI-SWIGGY7538@OKAXIS         1
UPI-SWIGGY6053@OKAXIS         1
UPI-SWIGGY-3505@HDFCBANK      1
UPI-SWIGGY-0015@HDFCBANK      1
UPI-SWIGGY6013@OKAXIS         1
UPI-SWIGGY-8838@HDFCBANK      1
UPI-SWIGGY-9077@HDFCBANK      1
UPI-SWIGGY3466@OKAXIS         1
Name: count, dtype: int64

In [185]:
pd.set_option("display.max_rows", 100)

In [186]:
remaining = others["Description"].value_counts()
remaining

Description
POS SWIGGY BANGALORE         28
Swiggy*Order                 26
BHIM SWIGGY                  23
Amazon Pay India             19
AMAZONIN MARKETPLACE         15
ROPPEN TRANSPORTATION        14
UPI-AMAZONPAY@HDFCBANK       12
UPI-THIRDWAVE@OKAXIS         11
AMAZON IN                    10
AMAZON SELLER SVCS            9
TWC INDIA                     9
BMS MOVIE TICKETS             7
UPI-BOOKMYSHOW@HDFCBANK       4
FKART INTRNET                 4
AMAZON PRIME VIDEO            4
UPI-SWIGGY0226@OKAXIS         2
UPI-SWIGGY-6560@HDFCBANK      1
UPI-SWIGGY-9474@HDFCBANK      1
UPI-SWIGGY-2954@HDFCBANK      1
UPI-SWIGGY-5808@HDFCBANK      1
UPI-SWIGGY-5551@HDFCBANK      1
UPI-SWIGGY-7959@HDFCBANK      1
UPI-SWIGGY2461@OKAXIS         1
UPI-SWIGGY9672@OKAXIS         1
UPI-SWIGGY4619@OKAXIS         1
UPI-SWIGGY3675@OKAXIS         1
UPI-SWIGGY1616@OKAXIS         1
UPI-SWIGGY-1309@HDFCBANK      1
UPI-SWIGGY-5933@HDFCBANK      1
UPI-SWIGGY8086@OKAXIS         1
UPI-SWIGGY-6605@HDFCBANK      1
UPI-SWIGGY-7844@HDFCBANK      1
UPI-SWIGGY-1487@HDFCBANK      1
UPI-SWIGGY-7642@HDFCBANK      1
UPI-SWIGGY-8169@HDFCBANK      1
UPI-SWIGGY1600@OKAXIS         1
UPI-SWIGGY8576@OKAXIS         1
UPI-SWIGGY5466@OKAXIS         1
UPI-SWIGGY-2664@HDFCBANK      1
UPI-SWIGGY5057@OKAXIS         1
UPI-SWIGGY4144@OKAXIS         1
UPI-SWIGGY-9575@HDFCBANK      1
UPI-SWIGGY9328@OKAXIS         1
UPI-SWIGGY9600@OKAXIS         1
UPI-SWIGGY-3513@HDFCBANK      1
UPI-SWIGGY1998@OKAXIS         1
UPI-SWIGGY0250@OKAXIS         1
UPI-SWIGGY0894@OKAXIS         1
UPI-SWIGGY6412@OKAXIS         1
UPI-SWIGGY-1791@HDFCBANK      1
UPI-SWIGGY5867@OKAXIS         1
UPI-SWIGGY-4758@HDFCBANK      1
UPI-SWIGGY4389@OKAXIS         1
UPI-SWIGGY8720@OKAXIS         1
UPI-SWIGGY9756@OKAXIS         1
UPI-SWIGGY-1714@HDFCBANK      1
UPI-SWIGGY-6024@HDFCBANK      1
UPI-SWIGGY5737@OKAXIS         1
UPI-AMAZON-PRIME@HDFCBANK     1
UPI-SWIGGY2847@OKAXIS         1
UPI-SWIGGY9088@OKAXIS         1
UPI-SWIGGY9983@OKAXIS         1
UPI-SWIGGY8392@OKAXIS         1
UPI-SWIGGY1418@OKAXIS         1
UPI-SWIGGY7538@OKAXIS         1
UPI-SWIGGY6053@OKAXIS         1
UPI-SWIGGY-3505@HDFCBANK      1
UPI-SWIGGY-0015@HDFCBANK      1
UPI-SWIGGY6013@OKAXIS         1
UPI-SWIGGY-8838@HDFCBANK      1
UPI-SWIGGY-9077@HDFCBANK      1
UPI-SWIGGY3466@OKAXIS         1
Name: count, dtype: int64

category dictionary

In [187]:
category_map = {}

In [188]:
category_map = {

    # Food Delivery
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Blinkit": "Quick Commerce",
    "Zepto": "Quick Commerce",
    "Instamart": "Quick Commerce",

    # Grocery
    "DMart": "Groceries",
    "BigBasket": "Groceries",

    # Shopping
    "Amazon": "Shopping",
    "Flipkart": "Shopping",
    "Myntra": "Shopping",
    "Meesho": "Shopping",
    "Ajio": "Shopping",

    # Coffee & Cafe
    "Third Wave": "Cafe",
    "Starbucks": "Cafe",

    # Entertainment
    "BookMyShow": "Entertainment",
    "Netflix": "Entertainment",
    "Spotify": "Entertainment",
    "Prime Video": "Entertainment",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "Roppen": "Transport",

    # Fuel
    "Indian Oil": "Fuel",
    "HPCL": "Fuel",
    "BPCL": "Fuel",

    # Bills & Recharge
    "Airtel": "Recharge",
    "Jio": "Recharge",
    "Vi": "Recharge",
    "BSNL": "Recharge",

    # Rent
    "Rent": "Rent",

    # Cash
    "ATM": "Cash Withdrawal",

    # Healthcare
    "Apollo": "Healthcare",
    "Pharmeasy": "Healthcare",

    # Investment
    "Groww": "Investment",
    "Zerodha": "Investment",
    "Upstox": "Investment",

    # Education
    "Udemy": "Education",
    "Coursera": "Education"
}

In [189]:
def get_category(description):

    description = str(description).upper()

    # Food Delivery
    if "SWIGGY" in description or "ZOMATO" in description:
        return "Food Delivery"

    # Quick Commerce
    elif ("ZEPTO" in description or
          "BLINKIT" in description or
          "INSTAMART" in description or
          "GROFERS" in description):
        return "Quick Commerce"

    # Shopping
    elif ("AMAZON" in description or
          "AMZN" in description or
          "FKART" in description or
          "FLIPKART" in description or
          "MYNTRA" in description or
          "NYKAA" in description):
        return "Shopping"

    # Groceries
    elif ("DMART" in description or
          "BIGBASKET" in description or
          "SUPERMART" in description or
          "KIRANAKART" in description or
          "INNOVATIVE RETAIL" in description):
        return "Groceries"

    # Cafe
    elif ("STARBUCKS" in description or
          "THIRD WAVE" in description or
          "THIRDWAVE" in description or
          "TWC" in description or
          "CCD" in description or
          "COFFEE DAY" in description):
        return "Cafe"

    # Restaurants
    elif ("RESTAURANT" in description or
          "MEGHANA" in description or
          "EMPIRE" in description or
          "TRUFFLES" in description or
          "DINEOUT" in description):
        return "Restaurants"

    # Transport
    elif ("RAPIDO" in description or
          "ROPPEN" in description or
          "UBER" in description or
          "OLA" in description or
          "BMTC" in description or
          "TUMMOC" in description):
        return "Transport"

    # Fuel
    elif ("INDIAN OIL" in description or
          "PETROL" in description or
          "HP" in description):
        return "Fuel"

    # Utilities
    elif ("BESCOM" in description or
          "ELEC" in description or
          "BWSSB" in description or
          "WATER BILL" in description):
        return "Utilities"

    # Investment
    elif ("GROWW" in description or
          "ZERODHA" in description):
        return "Investment"

    # Subscription
    elif ("PRIME" in description or
          "NETFLIX" in description or
          "SPOTIFY" in description or
          "HOTSTAR" in description or
          "DISNEY" in description):
        return "Subscription"

    # Salary
    elif "SALARY" in description:
        return "Salary"

    # Recharge
    elif ("AIRTEL" in description or
          "JIO" in description):
        return "Recharge"

    # Cash Withdrawal
    elif "ATM" in description:
        return "Cash Withdrawal"

    # Rent
    elif "RENT" in description:
        return "Rent"

    else:
        return "Others"

In [190]:
df["Category"] = df["Description"].apply(get_category)

df["Category"].value_counts()

Category
Food Delivery      317
Transport          232
Shopping           169
Quick Commerce     142
Cafe                99
Others              87
Restaurants         73
Groceries           54
Subscription        28
Investment          23
Utilities           23
Fuel                22
Cash Withdrawal     17
Recharge            12
Salary               6
Rent                 6
Name: count, dtype: int64

Executive Summary

In [191]:
# Income and Expense Summary

total_income = df[df["Type"] == "Credit"]["Amount"].sum()

total_expense = df[df["Type"] == "Debit"]["Amount"].sum()

net_savings = total_income - total_expense

saving_rate = (net_savings / total_income) * 100

In [192]:
print("="*65)
print("               EXECUTIVE SUMMARY")
print("="*65)

print(f"Total Transactions : {len(df)}")

print(f"Total Income       : ₹{total_income:,.2f}")

print(f"Total Expense      : ₹{total_expense:,.2f}")

print(f"Net Savings        : ₹{net_savings:,.2f}")

print(f"Savings Rate       : {saving_rate:.2f}%")

=================================================================
               EXECUTIVE SUMMARY
=================================================================
Total Transactions : 1310
Total Income       : ₹509,774.00
Total Expense      : ₹1,678,901.00
Net Savings        : ₹-1,169,127.00
Savings Rate       : -229.34%

Spending Categories

In [193]:
expense = df[df["Type"] == "Debit"]

category_spending = (
    expense
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

top_categories = category_spending.head(5)

In [194]:
print("="*65)
print("TOP 5 SPENDING CATEGORIES")
print("="*65)

for cat, amount in top_categories.items():
    print(f"{cat:<25} ₹{amount:,.2f}")

=================================================================
TOP 5 SPENDING CATEGORIES
=================================================================
Shopping                  ₹599,581.00
Investment                ₹248,160.00
Food Delivery             ₹139,023.00
Restaurants               ₹117,737.00
Rent                      ₹108,000.00

Top Vendors

In [195]:
top_vendors = (
    expense
    .groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

In [196]:
print("="*65)
print("TOP 5 VENDORS")
print("="*65)

for vendor, amount in top_vendors.items():
    print(f"{vendor:<20} ₹{amount:,.2f}")

=================================================================
TOP 5 VENDORS
=================================================================
Others               ₹377,597.00
Zerodha              ₹210,000.00
Flipkart             ₹170,745.00
Rent                 ₹108,000.00
Myntra               ₹69,529.00

Monthly Spending Trend

In [197]:
monthly_spending = (
    df[df["Type"] == "Debit"]
    .groupby("Month_Name")["Amount"]
    .sum()
)

# Display months in calendar order
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly_spending = monthly_spending.reindex(month_order).dropna()

monthly_spending

Month_Name
January     290767.0
February    234071.0
March       330458.0
April       251382.0
May         277306.0
June        294917.0
Name: Amount, dtype: float64

In [198]:
monthly_change = monthly_spending.pct_change() * 100

monthly_change = monthly_change.round(2)

monthly_change

Month_Name
January       NaN
February   -19.50
March       41.18
April      -23.93
May         10.31
June         6.35
Name: Amount, dtype: float64

In [199]:
highest_month = monthly_spending.idxmax()
highest_amount = monthly_spending.max()

lowest_month = monthly_spending.idxmin()
lowest_amount = monthly_spending.min()

In [200]:
print("="*65)
print("MONTHLY SPENDING TREND")
print("="*65)

for month, amount in monthly_spending.items():
    print(f"{month:<12} ₹{amount:,.2f}")

print("\nHighest Spending Month :", highest_month)
print(f"Amount : ₹{highest_amount:,.2f}")

print("\nLowest Spending Month :", lowest_month)
print(f"Amount : ₹{lowest_amount:,.2f}")

=================================================================
MONTHLY SPENDING TREND
=================================================================
January      ₹290,767.00
February     ₹234,071.00
March        ₹330,458.00
April        ₹251,382.00
May          ₹277,306.00
June         ₹294,917.00

Highest Spending Month : March
Amount : ₹330,458.00

Lowest Spending Month : February
Amount : ₹234,071.00

Spending by Day of Week

In [201]:
day_spending = (
    df[df["Type"] == "Debit"]
    .groupby("Day_Name")["Amount"]
    .sum()
)

day_order = [
    "Monday","Tuesday","Wednesday",
    "Thursday","Friday","Saturday","Sunday"
]

day_spending = day_spending.reindex(day_order)

day_spending

Day_Name
Monday       254099.0
Tuesday      265529.0
Wednesday    307364.0
Thursday     187390.0
Friday       188350.0
Saturday     259715.0
Sunday       216454.0
Name: Amount, dtype: float64

In [202]:
print("="*65)
print("SPENDING BY DAY")
print("="*65)

for day, amount in day_spending.items():
    print(f"{day:<12} ₹{amount:,.2f}")

=================================================================
SPENDING BY DAY
=================================================================
Monday       ₹254,099.00
Tuesday      ₹265,529.00
Wednesday    ₹307,364.00
Thursday     ₹187,390.00
Friday       ₹188,350.00
Saturday     ₹259,715.00
Sunday       ₹216,454.00

Time Pattern Analysis

In [203]:
hourly_spending = (
    df[df["Type"] == "Debit"]
    .groupby("Hour")["Amount"]
    .sum()
    .sort_index()
)

hourly_spending

Hour
0      37969.0
1      38882.0
2      20283.0
3      34868.0
4      43901.0
5      33671.0
6      55506.0
7      19938.0
8      41399.0
9      86701.0
10    140526.0
11    123389.0
12     77096.0
13    113819.0
14    121010.0
15     39647.0
16    100597.0
17     56604.0
18    101343.0
19     67848.0
20    138089.0
21     81545.0
22     55867.0
23     48403.0
Name: Amount, dtype: float64

In [204]:
peak_hour = hourly_spending.idxmax()
peak_amount = hourly_spending.max()

print("="*65)
print("HOURLY SPENDING")
print("="*65)

for hour, amount in hourly_spending.items():
    print(f"{hour:02d}:00 - ₹{amount:,.2f}")

print("\nPeak Spending Hour :", f"{peak_hour:02d}:00")
print(f"Amount : ₹{peak_amount:,.2f}")

=================================================================
HOURLY SPENDING
=================================================================
00:00 - ₹37,969.00
01:00 - ₹38,882.00
02:00 - ₹20,283.00
03:00 - ₹34,868.00
04:00 - ₹43,901.00
05:00 - ₹33,671.00
06:00 - ₹55,506.00
07:00 - ₹19,938.00
08:00 - ₹41,399.00
09:00 - ₹86,701.00
10:00 - ₹140,526.00
11:00 - ₹123,389.00
12:00 - ₹77,096.00
13:00 - ₹113,819.00
14:00 - ₹121,010.00
15:00 - ₹39,647.00
16:00 - ₹100,597.00
17:00 - ₹56,604.00
18:00 - ₹101,343.00
19:00 - ₹67,848.00
20:00 - ₹138,089.00
21:00 - ₹81,545.00
22:00 - ₹55,867.00
23:00 - ₹48,403.00

Peak Spending Hour : 10:00
Amount : ₹140,526.00

In [205]:
def get_time_period(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 22:
        return "Evening"

    else:
        return "Night"

In [206]:
df["Time_Period"] = df["Hour"].apply(get_time_period)

In [207]:
time_period_spending = (
    df[df["Type"] == "Debit"]
    .groupby("Time_Period")["Amount"]
    .sum()
)

print("="*65)
print("SPENDING BY TIME OF DAY")
print("="*65)

for period, amount in time_period_spending.items():
    print(f"{period:<12} ₹{amount:,.2f}")

=================================================================
SPENDING BY TIME OF DAY
=================================================================
Afternoon    ₹452,169.00
Evening      ₹445,429.00
Morning      ₹501,130.00
Night        ₹280,173.00

Anomaly Detection

In [208]:
expense = df[df["Type"]=="Debit"].copy()

mean = expense["Amount"].mean()

std = expense["Amount"].std()

expense["Z_Score"] = (
    expense["Amount"] - mean
) / std

In [209]:
anomalies = expense[expense["Z_Score"] > 3]

anomalies[
    ["Date","Description","Amount","Z_Score"]
]

           Date                  Description   Amount   Z_Score
34   2024-01-05  IMPS-RENT-LANDLORD-75500265  18000.0  5.961092
50   2024-01-07        UPI-ZERODHA-COIN@AXIS  15000.0  4.891038
70   2024-01-09          UPI-MYNTRA@HDFCBANK  10745.0  3.373345
129  2024-01-19         NEFT ZERODHA BROKING  15000.0  4.891038
169  2024-01-24               FLIPKART INDIA  16260.0  5.340460
171  2024-01-24     POS INDIAN OIL BANGALORE  10408.0  3.253142
248  2024-02-05  IMPS-RENT-LANDLORD-39598076  18000.0  5.961092
269  2024-02-07       UPI-AMAZONPAY@HDFCBANK  21986.0  7.382836
272  2024-02-08            IMPS ZERODHA-COIN  15000.0  4.891038
336  2024-02-17       UPI-AMAZONPAY@HDFCBANK  13674.0  4.418074
444  2024-03-02            IMPS ZERODHA-COIN  15000.0  4.891038
450  2024-03-02                    AMAZON IN  18273.0  6.058466
456  2024-03-03  IMPS-RENT-LANDLORD-51148088  18000.0  5.961092
475  2024-03-05       UPI-AMAZONPAY@HDFCBANK  19917.0  6.644856
486  2024-03-07        UPI-ZERODHA-COIN@AXIS  15000.0  4.891038
519  2024-03-12            IMPS ZERODHA-COIN  15000.0  4.891038
541  2024-03-14     POS INDIAN OIL BANGALORE  10505.0  3.287740
617  2024-03-26               ZERODHA-MF SIP  15000.0  4.891038
651  2024-03-31         AMAZONIN MARKETPLACE  15953.0  5.230958
695  2024-04-05  IMPS-RENT-LANDLORD-36852906  18000.0  5.961092
699  2024-04-05        UPI-FLIPKART@HDFCBANK  14305.0  4.643142
713  2024-04-08            IMPS ZERODHA-COIN  15000.0  4.891038
754  2024-04-13            IMPS ZERODHA-COIN  15000.0  4.891038
781  2024-04-17        UPI-ZERODHA-COIN@AXIS  15000.0  4.891038
875  2024-04-30             Amazon Pay India  14886.0  4.850376
913  2024-05-05  IMPS-RENT-LANDLORD-49966195  18000.0  5.961092
925  2024-05-07            IMPS ZERODHA-COIN  15000.0  4.891038
971  2024-05-13          UPI-MYNTRA@HDFCBANK  11565.0  3.665826
984  2024-05-15        UPI-FLIPKART@HDFCBANK  14416.0  4.682734
1007 2024-05-18               MYNTRA DESIGNS  11391.0  3.603763
1010 2024-05-18        UPI-ZERODHA-COIN@AXIS  15000.0  4.891038
1041 2024-05-22           ZERODHA SECURITIES  15000.0  4.891038
1079 2024-05-27        UPI-FLIPKART@HDFCBANK  17831.0  5.900812
1128 2024-06-03  IMPS-RENT-LANDLORD-35126704  18000.0  5.961092
1130 2024-06-03        UPI-FLIPKART@HDFCBANK  16369.0  5.379339
1144 2024-06-05             Amazon Pay India  14874.0  4.846095
1162 2024-06-08               ZERODHA-MF SIP  15000.0  4.891038
1291 2024-06-25             Amazon Pay India  17504.0  5.784176
1298 2024-06-26         AMAZONIN MARKETPLACE  22008.0  7.390683
1308 2024-06-27               FLIPKART INDIA  15955.0  5.231671

In [210]:
print("="*65)
print("ANOMALOUS TRANSACTIONS")
print("="*65)

print(f"Total Anomalies : {len(anomalies)}")

if len(anomalies) > 0:
    print("\nTop Anomalies\n")

    print(
        anomalies[
            ["Date","Description","Amount"]
        ].head(10)
    )

=================================================================
ANOMALOUS TRANSACTIONS
=================================================================
Total Anomalies : 40

Top Anomalies

          Date                  Description   Amount
34  2024-01-05  IMPS-RENT-LANDLORD-75500265  18000.0
50  2024-01-07        UPI-ZERODHA-COIN@AXIS  15000.0
70  2024-01-09          UPI-MYNTRA@HDFCBANK  10745.0
129 2024-01-19         NEFT ZERODHA BROKING  15000.0
169 2024-01-24               FLIPKART INDIA  16260.0
171 2024-01-24     POS INDIAN OIL BANGALORE  10408.0
248 2024-02-05  IMPS-RENT-LANDLORD-39598076  18000.0
269 2024-02-07       UPI-AMAZONPAY@HDFCBANK  21986.0
272 2024-02-08            IMPS ZERODHA-COIN  15000.0
336 2024-02-17       UPI-AMAZONPAY@HDFCBANK  13674.0

Spending Archetypes

In [211]:
archetypes = []

In [212]:
food_categories = ["Food Delivery", "Restaurants", "Cafe"]

food_spending = category_spending[
    category_spending.index.isin(food_categories)
].sum()

food_percentage = (food_spending / total_expense) * 100

if food_percentage >= 20:
    archetypes.append("🍔 Foodie")

In [213]:
shopping_categories = ["Shopping", "Quick Commerce", "Groceries"]

shopping_spending = category_spending[
    category_spending.index.isin(shopping_categories)
].sum()

shopping_percentage = (shopping_spending / total_expense) * 100

if shopping_percentage >= 25:
    archetypes.append("🛍️ Shopaholic")

In [214]:
investment = category_spending.get("Investment", 0)

if investment > 0:
    archetypes.append("📈 Investor")

In [215]:
cafe = category_spending.get("Cafe", 0)

if cafe > 1000:
    archetypes.append("☕ Coffee Lover")

In [216]:
night_spending = (
    df[
        (df["Type"]=="Debit") &
        (df["Time_Period"]=="Night")
    ]["Amount"].sum()
)

if night_spending > total_expense * 0.15:
    archetypes.append("🌙 Night Owl")

In [217]:
print("="*65)
print("SPENDING ARCHETYPES")
print("="*65)

if archetypes:
    for item in archetypes:
        print(item)
else:
    print("No dominant spending archetype identified.")

=================================================================
SPENDING ARCHETYPES
=================================================================
🛍️ Shopaholic
📈 Investor
☕ Coffee Lover
🌙 Night Owl

Final SpendDNA Report

In [218]:
print("="*70)
print("                  SPENDDNA REPORT")
print("="*70)

print("\nEXECUTIVE SUMMARY")
print("-"*70)
print(f"Transactions     : {len(df)}")
print(f"Income           : ₹{total_income:,.2f}")
print(f"Expense          : ₹{total_expense:,.2f}")
print(f"Savings          : ₹{net_savings:,.2f}")
print(f"Savings Rate     : {saving_rate:.2f}%")

print("\nTOP 5 CATEGORIES")
print("-"*70)
for cat, amt in top_categories.items():
    print(f"{cat:<25} ₹{amt:,.2f}")

print("\nTOP 5 VENDORS")
print("-"*70)
for vendor, amt in top_vendors.items():
    print(f"{vendor:<20} ₹{amt:,.2f}")

print("\nMONTHLY HIGHLIGHT")
print("-"*70)
print(f"Highest Spending Month : {highest_month}")
print(f"Lowest Spending Month  : {lowest_month}")

print("\nTIME PATTERN")
print("-"*70)
print(f"Peak Spending Hour : {peak_hour}:00")

print("\nANOMALIES")
print("-"*70)
print(f"Number of Unusual Transactions : {len(anomalies)}")

print("\nSPENDING ARCHETYPES")
print("-"*70)
if archetypes:
    for item in archetypes:
        print(item)
else:
    print("None")

print("="*70)

======================================================================
                  SPENDDNA REPORT
======================================================================

EXECUTIVE SUMMARY
----------------------------------------------------------------------
Transactions     : 1310
Income           : ₹509,774.00
Expense          : ₹1,678,901.00
Savings          : ₹-1,169,127.00
Savings Rate     : -229.34%

TOP 5 CATEGORIES
----------------------------------------------------------------------
Shopping                  ₹599,581.00
Investment                ₹248,160.00
Food Delivery             ₹139,023.00
Restaurants               ₹117,737.00
Rent                      ₹108,000.00

TOP 5 VENDORS
----------------------------------------------------------------------
Others               ₹377,597.00
Zerodha              ₹210,000.00
Flipkart             ₹170,745.00
Rent                 ₹108,000.00
Myntra               ₹69,529.00

MONTHLY HIGHLIGHT
----------------------------------------------------------------------
Highest Spending Month : March
Lowest Spending Month  : February

TIME PATTERN
----------------------------------------------------------------------
Peak Spending Hour : 10:00

ANOMALIES
----------------------------------------------------------------------
Number of Unusual Transactions : 40

SPENDING ARCHETYPES
----------------------------------------------------------------------
🛍️ Shopaholic
📈 Investor
☕ Coffee Lover
🌙 Night Owl
======================================================================

Project Insights

In [220]:
print("\nPROJECT INSIGHTS")
print("-"*70)

# 1 Highest Spending Category
print(f"1. The highest spending category was '{category_spending.idxmax()}', "
      f"accounting for ₹{category_spending.max():,.2f} of total expenses.")

# 2 Highest Spending Month
print(f"2. '{highest_month}' recorded the highest monthly expenditure, "
      f"while '{lowest_month}' had the lowest spending.")

# 3 Peak Spending Hour
print(f"3. Most transactions occurred around {peak_hour}:00, "
      "indicating this is the user's peak spending period.")

# 4 Savings
print(f"4. The user maintained a savings rate of {saving_rate:.2f}%, "
      "reflecting the balance between income and expenses.")

# 5 Spending Behaviour
if archetypes:
    print("5. Spending behaviour indicates the following archetype(s):")
    for item in archetypes:
        print(f"   • {item}")
else:
    print("5. No dominant spending archetype was identified.")

# 6 Anomalies
print(f"6. {len(anomalies)} unusually high-value transaction(s) were detected "
      "using Z-score analysis and may require further review.")

# 7 Most Preferred Vendor
print(f"7. The highest spending vendor was '{top_vendors.index[0]}', "
      f"with total spending of ₹{top_vendors.iloc[0]:,.2f}.")

PROJECT INSIGHTS
----------------------------------------------------------------------
1. The highest spending category was 'Shopping', accounting for ₹599,581.00 of total expenses.
2. 'March' recorded the highest monthly expenditure, while 'February' had the lowest spending.
3. Most transactions occurred around 10:00, indicating this is the user's peak spending period.
4. The user maintained a savings rate of -229.34%, reflecting the balance between income and expenses.
5. Spending behaviour indicates the following archetype(s):
   • 🛍️ Shopaholic
   • 📈 Investor
   • ☕ Coffee Lover
   • 🌙 Night Owl
6. 40 unusually high-value transaction(s) were detected using Z-score analysis and may require further review.
7. The highest spending vendor was 'Others', with total spending of ₹377,597.00.

# Reflection

This project helped me understand how transaction data can be transformed into meaningful financial insights. I learned data cleaning, feature engineering, category mapping, anomaly detection, behavioural analysis, and report generation using Python and pandas. The biggest challenge was accurately categorizing transaction descriptions into meaningful spending categories. By improving the categorization logic, I was able to generate a comprehensive financial behaviour report.

# AI Usage Statement

AI tools were used to assist with debugging, understanding pandas operations, improving code organization, and refining analysis logic. All data cleaning, feature engineering, implementation, validation, interpretation of results, and final report preparation were completed and verified by me.